# Generated by Django 5.2 on 2025-04-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='reiumbursed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='submitted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
